export const PREVIEW_NOTICE_CONTENT_LENGTH = 200;
export const PREVIEW_CONTENT_RATIO = 2;
export const LONGER_PREVIEW_CONTENT_RATIO = 3;
export const NOTICE_CONTENT_RATIO =
  PREVIEW_CONTENT_RATIO / LONGER_PREVIEW_CONTENT_RATIO;

export const VISIBLE_LATEST_NOTICES = 3;
