import { MEGABYTE } from './file';
import { HOUR, HOURS_IN_A_DAY, MINUTES_IN_AN_HOUR } from './date';

export const TASK_MAX_TITLE_LENGTH = 200;
export const TASK_MAX_MESSAGE_LENGTH = 500;
export const TASK_MAX_FILE_SIZE = 5 * MEGABYTE;
export const TASK_VISIBLE_SHORT_TITLE_LENGTH = 100;

export const MIN_TASK_DURATION_IN_MINUTES = 10;
export const MAX_TASK_DURATION_IN_MINUTES = 12 * HOUR;
export const MIN_HOMEWORK_DURATION_IN_MINUTES = 12 * HOUR;
export const DEFAULT_TASK_DURATION_IN_HOURS = 2;
export const DEFAULT_HOMEWORK_DURATION_IN_HOURS = HOURS_IN_A_DAY;

// POPRAWIC wartości
export const TASK_TASK_ENDING_SOON_TIME_IN_MINUTES = MINUTES_IN_AN_HOUR;
export const TASK_TASK_ENDING_VERY_SOON_TIME_IN_MINUTES = 20;
export const TASK_HOMEWORK_ENDING_SOON_TIME_IN_MINUTES =
  12 * MINUTES_IN_AN_HOUR;
export const TASK_HOMEWORK_ENDING_VERY_SOON_TIME_IN_MINUTES =
  3 * MINUTES_IN_AN_HOUR;

export const VISIBLE_LATEST_TASKS = 3;
export const TASK_LIST_PAGE_SIZE = 12;

export const TASK_DURATIONS = [
  15, 30, 45, 60, 90, 240, 480, 720, 1440, 2880, 4320,
];
